// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KioskCheckIn.Data.Models;

public partial class Administrator
{
    public string UserId { get; set; }

    public string Pin { get; set; }

    public string Username { get; set; }
}