// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KioskCheckIn.Data.Models;

public partial class Conference
{
    public int Id { get; set; }

    public string Name { get; set; }

    public DateOnly? From { get; set; }

    public DateOnly? To { get; set; }
}