// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace KioskCheckIn.Data.Models;

public partial class KioskContext : DbContext
{
    public KioskContext(DbContextOptions<KioskContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Administrator> Administrators { get; set; }

    public virtual DbSet<Conference> Conferences { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<UserSession> UserSessions { get; set; }

    public virtual DbSet<Visit> Visits { get; set; }

    public virtual DbSet<VisitType> VisitTypes { get; set; }

    public virtual DbSet<Visitor> Visitors { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Administrator>(entity =>
        {
            entity.HasKey(e => e.UserId).HasName("PK__Administ__1788CC4C71E3540A");

            entity.ToTable("Administrator");

            entity.Property(e => e.UserId).HasMaxLength(100);
            entity.Property(e => e.Pin)
                .IsRequired()
                .HasMaxLength(8)
                .HasColumnName("PIN");
            entity.Property(e => e.Username)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<Conference>(entity =>
        {
            entity
                .HasNoKey()
                .ToTable("Conference");

            entity.Property(e => e.Id).ValueGeneratedOnAdd();
            entity.Property(e => e.Name)
                .HasMaxLength(100)
                .IsUnicode(false);
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.UserId).HasName("PK__Users__1788CC4C2B89337C");

            entity.Property(e => e.Address).HasMaxLength(100);
            entity.Property(e => e.City).HasMaxLength(50);
            entity.Property(e => e.FirstName).HasMaxLength(100);
            entity.Property(e => e.LastName).HasMaxLength(100);
            entity.Property(e => e.State).HasMaxLength(50);
            entity.Property(e => e.Username)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.ZipCode).HasMaxLength(20);
        });

        modelBuilder.Entity<UserSession>(entity =>
        {
            entity.ToTable("UserSession");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.ActualSessionEnd).HasColumnType("datetime");
            entity.Property(e => e.ClientId).HasColumnName("ClientID");
            entity.Property(e => e.SessionEnd).HasColumnType("datetime");
            entity.Property(e => e.SessionStart).HasColumnType("datetime");
            entity.Property(e => e.Username)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<Visit>(entity =>
        {
            entity
                .HasNoKey()
                .ToTable("Visit");

            entity.Property(e => e.Id).ValueGeneratedOnAdd();
            entity.Property(e => e.VisitorId).HasColumnName("Visitor_ID");
        });

        modelBuilder.Entity<VisitType>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__VisitTyp__3214EC073A17DB95");

            entity.ToTable("VisitType");

            entity.Property(e => e.TypeOfVisit)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<Visitor>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Visitors__3214EC0792CEDB4B");

            entity.Property(e => e.CheckInTime).HasColumnType("datetime");
            entity.Property(e => e.ConferenceId).HasColumnName("Conference_ID");
            entity.Property(e => e.Email)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.FirstName).HasMaxLength(100);
            entity.Property(e => e.LastName).HasMaxLength(100);
            entity.Property(e => e.VisitTypeId).HasColumnName("VisitType_ID");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}