// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KioskCheckIn.Data.Models;

public partial class UserSession
{
    public int Id { get; set; }

    public int UserId { get; set; }

    public string Username { get; set; }

    public DateTime? SessionStart { get; set; }

    public DateTime? SessionEnd { get; set; }

    public DateTime? ActualSessionEnd { get; set; }

    public Guid? ClientId { get; set; }
}