// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KioskCheckIn.Data.Models;


public partial class Visitor
{
    private string _clearances = $"TOP SECRET/SCI, SECRET";
    private string _sas = $"Astro, NATO, COMSEC";
    private string _datStr;


    public int Id { get; set; }

    public string FirstName { get; set; }

    public string MiddleName { get; set; }

    public string LastName { get; set; }

    public DateTime? CheckInTime { get; set; }

    public int? ConferenceId { get; set; }

    public int? VisitTypeId { get; set; }

    public DateOnly? DateOfBirth { get; set; }
   
    public string DateOfBirthString
    {
        get => _datStr;
        set
        {
            _datStr = DateOfBirth.ToString();
        }
    }

    public string Email { get; set; }
    
    public string Employer { get; set; }
    
    public string Gender { get; set; }
    
    public string StreetAddress { get; set; }
    
    public string City { get; set; }
    
    public string State { get; set; }
    
    public string ZipCode { get; set; }
   
    public string Clearances
    {
        get => _clearances;
        set => _clearances = value;
    }

    public string SAs 
    {
        get => _sas;
        set => _sas = value;
    }
}
