// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KioskCheckIn.Data.Models;

public partial class Visit
{
    public int Id { get; set; }

    public int VisitorId { get; set; }

    public DateOnly? CheckInDateTime { get; set; }

    public DateOnly? CheckOutDateTime { get; set; }
}